### ISSUE TITLE
FeatureRequest: Add support for CLR

### ISSUE THREAD

**Issue by barnybadzoo** [ProjectMile/Mile.Project.Windows#1]
Hi,

i like this Project because it makes a lot easier.
can you add a configuration for supporting a clr Release of a dynamic dll.?

i need it to interop with .net. would be great!

**Comment by MouriNaruto** [comment]
I am happy you like it. I will try to add C++/CLI support in the recent days.

Kenji Mouri

**Comment by barnybadzoo** [comment]
This sounds great. Thank you👍

**Comment by MouriNaruto** [comment]
I hope https://github.com/ProjectMile/Mile.Project.Windows.Samples/tree/main/Mile.Samples.ClrConsoleApplication can make some help for you.

Kenji Mouri

**Comment by MouriNaruto** [comment]
It seems the issue should be fixed.

Kenji Mouri
